config/routes.rb
Riverboss::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root 'rivers#home_page'

  # Static Pages
  get 'about' => 'pages#about'
  get 'advertise' => 'pages#advertise'
  get 'disclaimer' => 'pages#disclaimer'
  get 'methodology' => 'pages#methodology'

  get '/html_view' => 'mobile#switch_to_html'
  get '/mobile_view' => 'mobile#switch_to_mobile'

  # Admin Routes
  namespace :admin do
    resources :rivers, only: [:index, :edit, :update] do
      get :search, on: :collection
    end
    resources :users, only: [:index]
    resources :regions, only: [:index]
    resources :states, only: [:index]
  end

  resources :pages, except: [:destroy, :add, :create]

  get 'contact' => 'contacts#new', as: 'contact'
  post 'contact' => 'contacts#create', as: 'contact_submit'

  get 'suggest' => 'suggest#new', as: 'suggest'
  post 'suggest' => 'suggest#create', as: 'suggest_submit'

  resources :posts

  resources :rivers, only: [:index, :show] do
    get :autocomplete, on: :collection
    get :near_by, on: :collection
    get :search, on: :collection
    get :popular, on: :collection
    get :default_conditions, on: :collection
  end

  resources :regions, only: [:index, :show]
  resources :states, only: [:index, :show]

  resources :users_rivers, except: [:show] do
    post :sort, on: :collection
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations' }, path: '', path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'user', sign_up: 'signup'}, sign_out_via: [:get]
end

app/models/users_river.rb
# == Schema Information
#
# Table name: users_rivers
#
#  id         :integer          not null, primary key
#  river_id   :integer
#  user_id    :integer
#  position   :integer
#  created_at :datetime
#  updated_at :datetime
#  conditions :hstore
#

class UsersRiver < ActiveRecord::Base

  belongs_to :user
  belongs_to :river

  validates :user_id, :river_id, presence: true
  validates :river_id, uniqueness: { scope: :user_id, message: "This river is already present in your My Rivers." }

  acts_as_list scope: :user

  after_create :set_position

  private

  def set_position
    self.move_to_top
  end

end

app/controllers/users_rivers_controller.rb
class UsersRiversController < ApplicationController

  before_action :authenticate_user

  def index
    @users_rivers = current_user.users_rivers.includes(:river)
    redirect_to new_users_river_path unless @users_rivers.any?
  end

  def create
    @user_river = UsersRiver.new(user_id: current_user.id, river_id: params[:river_id])
    if @user_river.save
      respond_to do |format|
        format.html {
          flash[:notice] = "#{@user_river.river.name} has been added to My Rivers."
          redirect_to users_rivers_path
        }
        format.json {
          render json: {status: 'success', url: edit_users_river_path(@user_river.river)}
        }
        format.mobile {
          flash[:notice] = "#{@user_river.river.name} has been added to My Rivers."
          redirect_to users_rivers_path
        }
      end
    else
      respond_to do |format|
        format.html {
          flash[:error] = check_duplicate_msg ? @user_river.errors.messages[:river_id][0] : "We couldn't add #{@user_river.river.name} to My Rivers, please try again."
          redirect_to users_rivers_path and return if check_duplicate_msg
          render 'new'
        }
        format.json {
          render json: {status: 'failure'}
        }
        format.mobile {
          flash[:error] = check_duplicate_msg ? @user_river.errors.messages[:river_id][0] : "We couldn't add #{@user_river.river.name} to My Rivers, please try again."
          redirect_to users_rivers_path and return if check_duplicate_msg
          render 'new'
        }
      end
    end
  end

  def sort
    @users_rivers = current_user.users_rivers
    @users_rivers.each do |ur|
      ur.position = params['users_river'].index(ur.id.to_s) + 1
      ur.save
    end
    render nothing: true
  end

  def destroy
    @user_river = current_user.users_rivers.find(params[:id])
    if @user_river.destroy!
      flash[:notice] = "#{@user_river.river.name} has been deleted from My Rivers."
      redirect_to users_rivers_path
    else
      flash[:error] = "We couldn't add #{@user_river.river.name} to My Rivers, please try again."
      render 'new'
    end
  end

  def edit
    # Caution - Sending River ID here not UserRiver ID
    river = River.find(params[:id])
    if current_user.rivers.pluck(:id).include? river.id
      user_river = current_user.users_rivers.find_by_river_id(river.id)
      result = render_to_string "shared/_users_river_condition", layout: false, locals: {river: river, user_river: user_river}
    else
      result = render_to_string "shared/_users_river_form", layout: false, locals: {river: river}
    end
    respond_to do |format|
      format.html
      format.json {
        render json: {result: result}
      }
      format.mobile {
        render json: {result: result}
      }
    end
  end

  def update
    @user_river = current_user.users_rivers.find params[:id]
    if params[:default] == "true"
      @user_river.conditions = @user_river.river.conditions
    else
      @user_river.conditions = {low: params[:user_river][:condition_low], high: params[:user_river][:condition_high]}
    end
    @user_river.save
    redirect_to params[:redirect_to] || users_rivers_path
  end

  private

  def check_duplicate_msg
    @user_river.errors.messages[:river_id][0] == "This river is already present in your My Rivers." ? true : false
  end

end

app/views/users_rivers/index.html.haml
- set_meta_tags(description: "Manage My Rivers", title: "Manage My Rivers | RiverBoss")

.my-river-area
  .head-part
    = render "shared/river_buttons"
    %h1 Manage Rivers

  #add_river_result.draggable
    - if @users_rivers.any?
      - @users_rivers.each do |ur|
        .river{id: "users_river_#{ur.id}"}
          .name{:style => "display: flex"}
            = button_to users_river_path(ur), method: :delete, class: "delete" do
              = image_tag "delete.png", width: 16
            &nbsp;
            &nbsp;
            = link_to ur.river.name, river_path(ur.river)
          .form-holder
            = suggest_tag ur.river, "Edit"
            &nbsp;
            &nbsp;
            %span.drag-handle= image_tag "drag.png", width: 16
    - else
      %h3 Sorry we coundn't find any river.

app/views/users_rivers/index.mobile.haml
- set_meta_tags(description: "Manage My Rivers", title: "Manage My Rivers | RiverBoss")

%section#content
  .content-holder
    = render "shared/river_buttons"
    %h1 Manage Rivers

  .gen-pad
    #add_river_result.draggable
      - if @users_rivers.any?
        - @users_rivers.each do |ur|
          .river{id: "users_river_#{ur.id}"}
            .name
              = link_to ur.river.name, river_path(ur.river)
            .form-holder.clearfix
              = button_to users_river_path(ur), method: :delete, class: "delete" do
                = image_tag "delete.png", width: 24
              = suggest_tag ur.river, "Edit"
              %span.drag-handle= image_tag "drag.png", width: 24
      - else
        %h3 Sorry we coundn't find any river.

app/views/users_rivers/new.html.haml
- set_meta_tags(description: "Add rivers to My Rivers", title: "Add rivers to My Rivers | RiverBoss")

.my-river-area
  .head-part
    = render "shared/river_buttons"
    %h1 Add Rivers

  .form-inputs
    .text.spinner-holder
      = text_field_tag :add_rivers_search, nil, placeholder: "Begin typing to search rivers", data: {url: autocomplete_rivers_url}
      .spinner
    .helper-text You can add items to My Rivers after searching

  #add_river_result

  %script#add_river_result_tmpl{ type: "text/x-tmpl" }
    .river
      .name= link_to "{%= o.river_name %}", "/rivers/{%= o.river_id %}"
      .form-holder
        %form{action: users_rivers_path, method: :post}
          = hidden_field_tag :river_id, "{%= o.river_id %}"
          = hidden_field_tag :authenticity_token, form_authenticity_token
          .form-actions= submit_tag "Save to my Rivers"

app/views/users_rivers/new.mobile.haml
- set_meta_tags(description: "Add rivers to My Rivers", title: "Add rivers to My Rivers | RiverBoss")

%section#content
  .content-holder
    = render "shared/river_buttons"
    %h1 Add Rivers

  .gen-pad
    .form-inputs
      .text.spinner-holder
        = text_field_tag :add_rivers_search, nil, placeholder: "Begin typing to search rivers", data: {url: autocomplete_rivers_url}
        .spinner
      .helper-text You can add items to My Rivers after searching

    #add_river_result

  %script#add_river_result_tmpl{ type: "text/x-tmpl" }
    .river
      .name= link_to "{%= o.river_name %}", "/rivers/{%= o.river_id %}"
      .form-holder
        %form{action: users_rivers_path, method: :post}
          = hidden_field_tag :river_id, "{%= o.river_id %}"
          = hidden_field_tag :authenticity_token, form_authenticity_token
          .form-actions= submit_tag "Save to my Rivers"