config/routes.rb
Riverboss::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root 'rivers#home_page'

  # Static Pages
  get 'about' => 'pages#about'
  get 'advertise' => 'pages#advertise'
  get 'disclaimer' => 'pages#disclaimer'
  get 'methodology' => 'pages#methodology'

  get '/html_view' => 'mobile#switch_to_html'
  get '/mobile_view' => 'mobile#switch_to_mobile'

  # Admin Routes
  namespace :admin do
    resources :rivers, only: [:index, :edit, :update] do
      get :search, on: :collection
    end
    resources :users, only: [:index]
    resources :regions, only: [:index]
    resources :states, only: [:index]
  end

  resources :pages, except: [:destroy, :add, :create]

  get 'contact' => 'contacts#new', as: 'contact'
  post 'contact' => 'contacts#create', as: 'contact_submit'

  get 'suggest' => 'suggest#new', as: 'suggest'
  post 'suggest' => 'suggest#create', as: 'suggest_submit'

  resources :posts

  resources :rivers, only: [:index, :show] do
    get :autocomplete, on: :collection
    get :near_by, on: :collection
    get :search, on: :collection
    get :popular, on: :collection
    get :default_conditions, on: :collection
  end

  resources :regions, only: [:index, :show]
  resources :states, only: [:index, :show]

  resources :users_rivers, except: [:show] do
    post :sort, on: :collection
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations' }, path: '', path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'user', sign_up: 'signup'}, sign_out_via: [:get]
end

app/models/suggest.rb
class Suggest < MailForm::Base

  attributes :name, validate: true
  attributes :email, validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attributes :river_name, validate: true
  attributes :condition_high, validate: true
  attributes :condition_low, validate: true
  attributes :nickname, captcha: true
  attributes :comment

  def headers
    {
      subject: "RiverBoss Condition Suggest Request",
      to: "admin@riverboss.com",
      from: %("RiverBoss Condition Suggest Request" <no-reply@riverboss.com>),
      reply_to: %("#{name}" <#{email}>)
    }
  end

end

app/controllers/suggest_controller.rb
class SuggestController < ApplicationController

  def new; end

  def create
    @suggest = Suggest.new(params[:suggest])
    @suggest.request = request
    if @suggest.deliver
      redirect_to root_path, notice: "We have recieved you suggestion, Thank you."
    else
      flash[:alert] = "Something went wrong, please try again."
      render 'new'
    end
  end

end

app/views/suggest/new.html.haml
- set_meta_tags(description: "Suggest #{params[:river_name] || "River"} Condition to RiverBoss", title: "Suggest #{params[:river_name] || "River"} Condition | RiverBoss")

.my-river-area
  .head-part
    %h1 Suggest #{params[:river_name] || "River"} Discharge Condition
    %p{style: "max-width: 400px"} If you are familiar with a specific river and you would like to share your knowlege, please complete the form below.

= simple_form_for Suggest.new, url: suggest_submit_path do |f|
  .form-inputs
    - if params[:river_name].present?
      = f.input :river_name, readonly: true, input_html: {value: params[:river_name]}
    - else
      .text.spinner-holder
        = f.input :river_name, required: true, placeholder: "Begin typing to search rivers", input_html: {class: "river-autocomplete", data: {url: autocomplete_rivers_url}}
        .spinner.top-margined

    .condition
      %label
        %span * River Conditions
        = text_field_tag :river_condition_low, 300, name: "suggest[condition_low]", readonly: true
        %span -
        = text_field_tag :river_condition_high, 3000, name: "suggest[condition_high]", readonly: true
      #condition_filter

    = f.input :name, required: true
    = f.input :email, required: true
    = f.input :comment, as: :text
  %div{style: "display: none"}
    = f.input :nickname
  .form-actions
    = f.button :submit, 'SEND', data: { disable_with: "Sending Email..." }

app/views/suggest/new.mobile.haml
- set_meta_tags(description: "Suggest #{params[:river_name] || "River"} Condition to RiverBoss", title: "Suggest #{params[:river_name] || "River"} Condition | RiverBoss")

%section#content
  .content-holder
    %h1 Suggest #{params[:river_name] || "River"} Discharge Condition
    %p{style: "max-width: 400px"} If you are familiar with a specific river and you would like to share your knowlege, please complete the form below.

  .gen-pad
    = simple_form_for Suggest.new, url: suggest_submit_path do |f|
      .form-inputs

        - if params[:river_name].present?
          = f.input :river_name, readonly: true, input_html: {value: params[:river_name]}
        - else
          .text.spinner-holder
            = f.input :river_name, required: true, placeholder: "Begin typing to search rivers", input_html: {class: "river-autocomplete", data: {url: autocomplete_rivers_url}}
            .spinner.top-margined

        .condition
          %label
            %span * River Conditions
            = text_field_tag :river_condition_low, 300, name: "suggest[condition_low]", readonly: true
            %span -
            = text_field_tag :river_condition_high, 3000, name: "suggest[condition_high]", readonly: true
          #condition_filter

        = f.input :name, required: true
        = f.input :email, required: true
        = f.input :comment, as: :text
      %div{style: "display: none"}
        = f.input :nickname
      .form-actions
        = f.button :submit, 'SEND', data: { disable_with: "Sending Email..." }, class: :btn