config/routes.rb
Riverboss::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root 'rivers#home_page'

  # Static Pages
  get 'about' => 'pages#about'
  get 'advertise' => 'pages#advertise'
  get 'disclaimer' => 'pages#disclaimer'
  get 'methodology' => 'pages#methodology'

  get '/html_view' => 'mobile#switch_to_html'
  get '/mobile_view' => 'mobile#switch_to_mobile'

  # Admin Routes
  namespace :admin do
    resources :rivers, only: [:index, :edit, :update] do
      get :search, on: :collection
    end
    resources :users, only: [:index]
    resources :regions, only: [:index]
    resources :states, only: [:index]
  end

  resources :pages, except: [:destroy, :add, :create]

  get 'contact' => 'contacts#new', as: 'contact'
  post 'contact' => 'contacts#create', as: 'contact_submit'

  get 'suggest' => 'suggest#new', as: 'suggest'
  post 'suggest' => 'suggest#create', as: 'suggest_submit'

  resources :posts

  resources :rivers, only: [:index, :show] do
    get :autocomplete, on: :collection
    get :near_by, on: :collection
    get :search, on: :collection
    get :popular, on: :collection
    get :default_conditions, on: :collection
  end

  resources :regions, only: [:index, :show]
  resources :states, only: [:index, :show]

  resources :users_rivers, except: [:show] do
    post :sort, on: :collection
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations' }, path: '', path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'user', sign_up: 'signup'}, sign_out_via: [:get]
end

app/views/shared/_about.html.haml
%h2 Welcome
%p
  Thanks for visiting RiverBoss 3.0. Our goal is to provide river anglers, rafters and boaters with the intelligence you need to make your next river trip safe and successful. Don’t forget to
  = link_to "register", new_user_registration_path
  to receive full access to RiverBoss.com features. See you on the river!

%h2 Learn More
%p
  Check out our
  = link_to "User Guide", "/pages/user-guide"
  to learn more about RiverBoss features and functionality. Or visit our
  = link_to "About page", "/pages/about"
  to learn how we built and populated this website and it's history.

app/views/shared/_home_page_info.html.haml
%section#two-columns
  %article.column
    = render "shared/about"
  .column
    = render "shared/recent_news"

app/views/shared/_newsletter_form.html.haml
%h2 newsletter
%p Sign-up for our newsletter and receive new, updates and river information via email.
%form.email-form
  %fieldset
    %input{placeholder: "email address", type: "email"}/
    %input{type: "submit", value: "GO"}/

app/views/shared/_recent_news.html.haml
- recent_news = Post.where(status: "Published").limit(4).order("created_at DESC")

%h2 News & Updates
%ul
  - Post.recent.each do |n|
    - cache n do
      %li
        .head-part
          = link_to n.title, n
          %span= l n.created_at, format: :blog_date
        %p= truncate strip_tags(n.content).html_safe, length: 200

= link_to "Read more news...", posts_path

app/views/shared/_river_buttons.html.haml
%ul
  %li
    = link_to "Add rivers", new_users_river_path, class: :btn
  %li
    = link_to "Manage", users_rivers_path, class: :btn

app/views/shared/_river_buttons.mobile.haml
.btn-holder
  - if user_signed_in?
    = link_to "Add Rivers", new_users_river_path, class: :btn
    = link_to "Manage", users_rivers_path, class: :btn
  - else
    = link_to "Add Rivers", new_user_session_path(redirect_to: new_users_river_path), class: :btn
    = link_to "Manage", new_user_session_path(redirect_to: users_rivers_path), class: :btn

app/views/shared/_river_list.html.haml
- rivers ||= @rivers
- no_pagination ||= false

- if rivers.any?
  %table.table.big.hovered
    - @rivers.each do |s|
      %tr
        %td= link_to s.name, river_path(s)
  %br/
  = paginate rivers unless no_pagination
- else
  %h3 Sorry, we couldn’t find any rivers that match your search terms.

app/views/shared/_river_list.mobile.haml
- rivers ||= @rivers
- no_pagination ||= false

- if rivers.any?
  %table
    - @rivers.each do |s|
      %tr
        %td.col1= link_to s.name, river_path(s)
  %br/
  = paginate rivers unless no_pagination
- else
  .gen-pad
    %h3 Sorry, we couldn’t find any rivers that match your search terms.

app/views/shared/_river_table.html.haml
- rivers ||= @rivers
- no_pagination ||= false
- tomorrow = Date.tomorrow
- next_next_day = Date.tomorrow + 1.day

- if rivers.any?
  %table.table.river-table
    %thead
      %tr
        %th.col1 River/Stream
        %th.col2 CFS
        %th.col3 Ht
        %th.col4 °F
        %th.col5 Cond
        %th.col6 Now
        %th.col7= tomorrow.strftime("%a")
        %th.col8= next_next_day.strftime("%a")
        %th.col9 Sr/Ss
    %tbody
      - rivers.each do |r|
        - current_condition = r.weather["current_condition"] if r.weather.present?
        - forecast          = r.weather["forecast"] if r.weather.present?
        - tom_mor_forecast = forecast[tomorrow.strftime("%A")] if forecast.present?
        - tom_nig_forecast = forecast[tomorrow.strftime("%A") + " Night"] if forecast.present?
        - nex_mor_forecast = forecast[next_next_day.strftime("%A")] if forecast.present?
        - nex_nig_forecast = forecast[next_next_day.strftime("%A") + " Night"] if forecast.present?
        %tr.sunrise-sunset{data: {location: "#{r.city} #{r.state.name}"}}
          %td.col1
            = link_to r.name_short, river_path(r), class: "river-graph-show"
            .river-graph= image_tag "https://waterdata.usgs.gov/nwisweb/graph?agency_cd=USGS&site_no=#{r.site_no}&parm_cd=00060&period=7", width: 576, alt: "Not Found"
          %td.col2= check_nil r.discharge
          %td.col3= check_nil r.gauge_height.to_f.round(1)
          %td.col4= check_nil r.water_temp
          = find_discharge_status r
          %td.col6
            - if current_condition["icon"] && |
              current_condition["icon"].nil? |
              = image_tag "weather-icons/#{current_condition["icon"]}", width: 30 if current_condition.present?
              = (current_condition["temperature"].blank? ? "–" : current_condition["temperature"]) if current_condition.present?
          %td.col7
            = image_tag "weather-icons/#{tom_mor_forecast["icon"]}", width: 30 if tom_mor_forecast.present?
            .value-area
              %span= (tom_mor_forecast.blank? ? "–" : tom_mor_forecast["temperature"]) if forecast.present?
              = (tom_nig_forecast.blank? ? "–" : tom_nig_forecast["temperature"]) if forecast.present?
          %td.col8
            = image_tag "weather-icons/#{nex_mor_forecast["icon"]}", width: 30 if nex_mor_forecast.present?
            .value-area
              %span= (nex_mor_forecast.blank? ? "–" : nex_mor_forecast["temperature"]) if forecast.present?
              = (nex_nig_forecast.blank? ? "–" : nex_nig_forecast["temperature"]) if forecast.present?
          %td.col9
            %span.sunrise –
            %span.sunset
- else
  %h3 Sorry we coundn't find any river.

app/views/shared/_river_table.mobile.haml
- rivers ||= @rivers

- if rivers.any?
  %table.river_table
    %thead
      %tr
        %th.col1 River
        %th.col2
          %button{:type => "button", :value => "Ft CFS", class: "toggle_cfs_ft cfs"}
            CFS
            %span.color Ft
          %button{:type => "button", :value => "Ft CFS", class: "toggle_cfs_ft ft"}
            Ft
            %span.color CFS
        %th.col3 Condition
    %tbody
      - rivers.each do |r|
        %tr
          %td.col1= link_to truncate(r.name_short, length: 25), river_path(r), class: "river-graph-show"
          %td.col2
            %span.cfs= check_nil r.discharge
            %span.ft= check_nil r.gauge_height.to_f.round(1)
          = find_discharge_status r, "list", true
- else
  .gen-pad
    %h3 Sorry we coundn't find any river.

app/views/shared/_users_river_condition.html.haml
- custom_selected = user_river.conditions.present? || !river.conditions.present? ? true : false
- high_value = user_river.conditions.present? ? user_river.conditions["high"] : 3000
- low_value  = user_river.conditions.present? ? user_river.conditions["low"] : 300

.river-condition-form
  %h2 Edit River Condition Levels
  %p Use the controls below to configure custom or default river condition levels for:
  %h2= river.name

  = form_tag users_river_path(user_river), method: :put, id: "save_my_river_form" do
    = hidden_field_tag :redirect_to, params[:redirect_to]
    = hidden_field_tag :authenticity_token, form_authenticity_token
    - if river.conditions.present?
      .row
        .left
          %label
            %strong Default Condition Values
          = radio_button_tag :default, true, true
        .right
          Use RiverBoss recommended values for river conditions.
          %h3
            %span.low LOW
            = river.conditions["low"]
            &nbsp;
            &nbsp;
            &nbsp;
            &nbsp;
            %span.high HIGH
            = river.conditions["high"]

    .row
      .left
        %label
          %strong Custom River Conditions
          = radio_button_tag :default, false, custom_selected
      .right.condition.form-inputs
        Use the slider below to configure custom river condition values for '#{river.name}'
        .text-boxes
          = text_field_tag :river_condition_low, low_value, name: "user_river[condition_low]", readonly: true
          %span -
          = text_field_tag :river_condition_high, high_value, name: "user_river[condition_high]", readonly: true
        #condition_filter{data: {low_value: low_value, high_value: high_value}}

    .form-actions.text-center= submit_tag "Save to my Rivers"

app/views/shared/_users_river_condition.mobile.haml
- custom_selected = user_river.conditions.present? || !river.conditions.present? ? true : false
- high_value = user_river.conditions.present? ? user_river.conditions["high"] : 3000
- low_value  = user_river.conditions.present? ? user_river.conditions["low"] : 300

.river-condition-form
  %h2 Edit River Condition Levels
  %p Use the controls below to configure custom or default river condition levels for:
  %h2= river.name

  = form_tag users_river_path(user_river), method: :put, id: "save_my_river_form" do
    = hidden_field_tag :redirect_to, params[:redirect_to]
    = hidden_field_tag :authenticity_token, form_authenticity_token
    - if river.conditions.present?
      .row
        .left
          %label
            %strong Default Condition Values
          = radio_button_tag :default, true, true
        .right
          Use RiverBoss recommended values for river conditions.
          %h3
            %span.low LOW
            = river.conditions["low"]
            &nbsp;
            &nbsp;
            &nbsp;
            &nbsp;
            %span.high HIGH
            = river.conditions["high"]

    .row{style: "margin-top: 25px"}
      .left
        %label
          %strong Custom River Conditions
          = radio_button_tag :default, false, custom_selected
      .right.condition.form-inputs
        Use the slider below to configure custom river condition values for '#{river.name}'
        .text-boxes
          = text_field_tag :river_condition_low, low_value, name: "user_river[condition_low]", readonly: true
          %span -
          = text_field_tag :river_condition_high, high_value, name: "user_river[condition_high]", readonly: true
        #condition_filter{data: {low_value: low_value, high_value: high_value}}

    .form-actions.text-center= submit_tag "Save to my Rivers"

app/views/shared/_users_river_form.html.haml
%p
  River
  = "'#{river.name}'"
  is not aded to your 'My Rivers'. Please save it before configuring condition for this river.

%form{action: users_rivers_path, method: :post, data: {remote: true, type: :json}, id: "save_my_river_form"}
  = hidden_field_tag :river_id, river.id
  = hidden_field_tag :authenticity_token, form_authenticity_token
  .form-actions.text-center= submit_tag "Save to my Rivers"

app/views/shared/_users_river_form.mobile.haml
%p
  River
  = "'#{river.name}'"
  is not aded to your 'My Rivers'. Please save it before configuring condition for this river.

%form{action: users_rivers_path, method: :post, data: {remote: true, type: :json}, id: "save_my_river_form"}
  = hidden_field_tag :river_id, river.id
  = hidden_field_tag :authenticity_token, form_authenticity_token
  .form-actions.text-center= submit_tag "Save to my Rivers"